// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemRequestKPU.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324145638_migrationDataKPU")]
    partial class migrationDataKPU
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Complex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Complexes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Воткинск",
                            Name = "Газокомпрессорная станция",
                            Type = "ГКС"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Чайковский",
                            Name = "Газораспределительная станция",
                            Type = "ГРС"
                        });
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("FactoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TechnologicalUnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("TechnologicalUnitId");

                    b.ToTable("EquipmentInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStatus = "В работе",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "INV-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentStatus = "В работе",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "INV-002",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            CurrentStatus = "В работе",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "INV-003",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        });
                });

            modelBuilder.Entity("EquipmentParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccuracyClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentInstanceId")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<string>("MeasurementRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("NormalValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("EquipmentParameters");
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Siemens",
                            Model = "S7-1500",
                            Name = "Главный контроллер управления",
                            Specifications = "Управление ГПА"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "ABB",
                            Model = "AC800M",
                            Name = "Система автоматического управления",
                            Specifications = "АСУ ТП"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Emerson",
                            Model = "Rosemount",
                            Name = "Датчик оборотов двигателя",
                            Specifications = "Измерение оборотов"
                        });
                });

            modelBuilder.Entity("SistemRequestKPU.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplexId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGRS")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("TechnicalObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplexId = 1,
                            InstallationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsGRS = false,
                            Name = "Газокомпрессорная станция",
                            ObjectType = "ГКС"
                        },
                        new
                        {
                            Id = 2,
                            ComplexId = 2,
                            InstallationDate = new DateTime(2019, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsGRS = true,
                            Name = "Газораспределительная станция",
                            ObjectType = "ГРС"
                        });
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("TechnologicalUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ГПА-1.1",
                            Description = "Агрегат 1.1",
                            Name = "Газоперекачивающий агрегат №1.1",
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "ГПА-1.2",
                            Description = "Агрегат 1.2",
                            Name = "Газоперекачивающий агрегат №1.2",
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "ГПА-2.1",
                            Description = "Агрегат 2.1",
                            Name = "Газоперекачивающий агрегат №2.1",
                            WorkshopId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "РУ-1",
                            Description = "Редукционный узел",
                            Name = "Редукционный узел №1",
                            WorkshopId = 4
                        });
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsiblePersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsiblePersonId");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "КЦ1",
                            Name = "Компрессорный цех №1",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "КЦ2",
                            Name = "Компрессорный цех №2",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "КЦ3",
                            Name = "Компрессорный цех №3",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "РЦ1",
                            Name = "Распределительный цех №1",
                            ResponsiblePersonId = 1
                        });
                });

            modelBuilder.Entity("kursovou_wed.models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TechnologicalUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EquipmentInstanceId");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("TechnologicalUnitId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("kursovou_wed.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$cjdnnXGom3XXZpY7c2SRrOxs1G6GpW1N1UiM2mCQDWPeFgDTSHb82",
                            Role = 3,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dispatcher@example.com",
                            PasswordHash = "$2a$11$/34lK4o2aWth4tGo2KGElurDdrmj6sIbAtoXPNVKFRYKscuFRjoPm",
                            Role = 2,
                            Username = "dispatcher"
                        },
                        new
                        {
                            Id = 3,
                            Email = "executor1@example.com",
                            PasswordHash = "$2a$11$f5nbsKuxpbbiM2Irp7psoe8.pvL1.9156FNJSrlOsep3v1iLlm.y2",
                            Role = 1,
                            Username = "executor1"
                        },
                        new
                        {
                            Id = 4,
                            Email = "executor2@example.com",
                            PasswordHash = "$2a$11$h1GverJ.w5pCLv5tQIp8GekGrS2F957HT7bSkpQjmn5/OWX7pPXEK",
                            Role = 1,
                            Username = "executor2"
                        },
                        new
                        {
                            Id = 5,
                            Email = "applicant@example.com",
                            PasswordHash = "$2a$11$OE/VtaNlWxDLH8L89SWqQ.AsTgAi73q5pig47ta8zxIANWVAj8QKW",
                            Role = 0,
                            Username = "applicant"
                        });
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.HasOne("EquipmentType", "EquipmentType")
                        .WithMany("Instances")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany("EquipmentInstances")
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnologicalUnit", "TechnologicalUnit")
                        .WithMany("EquipmentInstances")
                        .HasForeignKey("TechnologicalUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentType");

                    b.Navigation("TechnicalObject");

                    b.Navigation("TechnologicalUnit");
                });

            modelBuilder.Entity("EquipmentParameter", b =>
                {
                    b.HasOne("EquipmentInstance", "EquipmentInstance")
                        .WithMany("Parameters")
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.HasOne("Complex", "Complex")
                        .WithMany("TechnicalObjects")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.HasOne("Workshop", "Workshop")
                        .WithMany("TechnologicalUnits")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.HasOne("kursovou_wed.models.User", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("kursovou_wed.models.Request", b =>
                {
                    b.HasOne("kursovou_wed.models.User", "Assignee")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssigneeId");

                    b.HasOne("kursovou_wed.models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany()
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnologicalUnit", "TechnologicalUnit")
                        .WithMany()
                        .HasForeignKey("TechnologicalUnitId");

                    b.HasOne("Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Creator");

                    b.Navigation("EquipmentInstance");

                    b.Navigation("TechnicalObject");

                    b.Navigation("TechnologicalUnit");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Complex", b =>
                {
                    b.Navigation("TechnicalObjects");
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.Navigation("EquipmentInstances");
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.Navigation("EquipmentInstances");
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.Navigation("TechnologicalUnits");
                });

            modelBuilder.Entity("kursovou_wed.models.User", b =>
                {
                    b.Navigation("AssignedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
