// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemRequestKPU.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Complex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Complexes");
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("FactoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TechnologicalUnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("TechnologicalUnitId");

                    b.ToTable("EquipmentInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStatus = "",
                            EquipmentTypeId = 1,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-КУ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentStatus = "",
                            EquipmentTypeId = 2,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-АСУ-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            CurrentStatus = "",
                            EquipmentTypeId = 3,
                            FactoryNumber = "",
                            InventoryNumber = "ГПА1.1-ДОД-001",
                            StationNumber = "",
                            TechnicalNumber = "",
                            TechnicalObjectId = 1,
                            TechnologicalUnitId = 1
                        });
                });

            modelBuilder.Entity("EquipmentParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccuracyClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentInstanceId")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<string>("MeasurementRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("NormalValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("EquipmentParameters");
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("SistemRequestKPU.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplexId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGRS")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("TechnicalObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplexId = 1,
                            IsGRS = false,
                            Name = "Газокомпрессорная станция",
                            ObjectType = "ГКС"
                        },
                        new
                        {
                            Id = 2,
                            ComplexId = 2,
                            IsGRS = true,
                            Name = "Газораспределительная станция",
                            ObjectType = "ГРС"
                        });
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("TechnologicalUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ГПА-1.1",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №1.1",
                            TechnicalObjectId = 1,
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "ГПА-1.2",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №1.2",
                            TechnicalObjectId = 1,
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "ГПА-2.1",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №2.1",
                            TechnicalObjectId = 1,
                            WorkshopId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "ГПА-2.2",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №2.2",
                            TechnicalObjectId = 1,
                            WorkshopId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "ГПА-3.1",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №3.1",
                            TechnicalObjectId = 1,
                            WorkshopId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "ГПА-3.2",
                            Description = "",
                            Name = "Газоперекачивающий агрегат №3.2",
                            TechnicalObjectId = 1,
                            WorkshopId = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "УОГ",
                            Description = "",
                            Name = "Узел очистки газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 4
                        },
                        new
                        {
                            Id = 8,
                            Code = "УРГ",
                            Description = "",
                            Name = "Узел редуцирования газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 4
                        },
                        new
                        {
                            Id = 9,
                            Code = "УПОГ",
                            Description = "",
                            Name = "Узел подогрева и одоризации газа",
                            TechnicalObjectId = 2,
                            WorkshopId = 4
                        });
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsiblePersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsiblePersonId");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "КЦ1",
                            Name = "Компрессорный цех №1",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "КЦ2",
                            Name = "Компрессорный цех №2",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "КЦ3",
                            Name = "Компрессорный цех №3",
                            ResponsiblePersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "РЦ1",
                            Name = "Распределительный цех №1",
                            ResponsiblePersonId = 1
                        });
                });

            modelBuilder.Entity("kursovou_wed.models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TechnologicalUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EquipmentInstanceId");

                    b.HasIndex("TechnicalObjectId");

                    b.HasIndex("TechnologicalUnitId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("kursovou_wed.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$woj0R5P2pi9VZdbeDO9ROezoiaaVSB8ZP2aKbEFgAouhByvgCXi1S",
                            Role = 3,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dispatcher@example.com",
                            PasswordHash = "$2a$11$T/q7iRi4Cb.Zdf5.WZ23.uIS0pKC7Pnpg2Ch9ZJnkPPo4j89Zws9G",
                            Role = 2,
                            Username = "dispatcher"
                        },
                        new
                        {
                            Id = 3,
                            Email = "executor1@example.com",
                            PasswordHash = "$2a$11$ka7hiJ520wOzTaOmmErT6.JWrQVHKPRlTZ7yyx/.Hzx6gsaSEqxWC",
                            Role = 1,
                            Username = "executor1"
                        },
                        new
                        {
                            Id = 4,
                            Email = "executor2@example.com",
                            PasswordHash = "$2a$11$8t3RMwBFgDrJLqpNxltqdejEnEAJoCOvn.4Skpw/H2vrx3xp.89ou",
                            Role = 1,
                            Username = "executor2"
                        },
                        new
                        {
                            Id = 5,
                            Email = "applicant@example.com",
                            PasswordHash = "$2a$11$RUllYUgwYwSuz/jj/1/OxOUk92OnyCntohSRLxbDuG20bvBmrenwW",
                            Role = 0,
                            Username = "applicant"
                        });
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.HasOne("EquipmentType", "EquipmentType")
                        .WithMany("Instances")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany("EquipmentInstances")
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnologicalUnit", "TechnologicalUnit")
                        .WithMany("EquipmentInstances")
                        .HasForeignKey("TechnologicalUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentType");

                    b.Navigation("TechnicalObject");

                    b.Navigation("TechnologicalUnit");
                });

            modelBuilder.Entity("EquipmentParameter", b =>
                {
                    b.HasOne("EquipmentInstance", "EquipmentInstance")
                        .WithMany("Parameters")
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.HasOne("Complex", "Complex")
                        .WithMany("TechnicalObjects")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany("TechnologicalUnits")
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Workshop", "Workshop")
                        .WithMany("TechnologicalUnits")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicalObject");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.HasOne("kursovou_wed.models.User", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("kursovou_wed.models.Request", b =>
                {
                    b.HasOne("kursovou_wed.models.User", "Assignee")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssigneeId");

                    b.HasOne("kursovou_wed.models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalObject", "TechnicalObject")
                        .WithMany()
                        .HasForeignKey("TechnicalObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnologicalUnit", "TechnologicalUnit")
                        .WithMany()
                        .HasForeignKey("TechnologicalUnitId");

                    b.HasOne("Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Creator");

                    b.Navigation("EquipmentInstance");

                    b.Navigation("TechnicalObject");

                    b.Navigation("TechnologicalUnit");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Complex", b =>
                {
                    b.Navigation("TechnicalObjects");
                });

            modelBuilder.Entity("EquipmentInstance", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("TechnicalObject", b =>
                {
                    b.Navigation("EquipmentInstances");

                    b.Navigation("TechnologicalUnits");
                });

            modelBuilder.Entity("TechnologicalUnit", b =>
                {
                    b.Navigation("EquipmentInstances");
                });

            modelBuilder.Entity("Workshop", b =>
                {
                    b.Navigation("TechnologicalUnits");
                });

            modelBuilder.Entity("kursovou_wed.models.User", b =>
                {
                    b.Navigation("AssignedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
